### ISSUE TITLE
chef_handler provider error with chef-client 13.0.113

### ISSUE THREAD

**Issue by Stromweld** [chef-cookbooks/chef_handler#50]
### Cookbook version
2.1.0

### Chef-client version
13.0.113

### Platform Details
CentOS 7.3.1611 hosted in AWS Cloud

### Scenario:
chef-run convergence

### Steps to Reproduce:
motd (0.6.4) cookbook depends on chef_handler. Simply create a server with motd::default in the runlist

### Expected Result:
/etc/motd file gets updated with chef info

### Actual Result:
This did work in previous chef-client v12.19.x.

Recipe: motd::knife_status
  * motd[98-knife-status] action create (skipped due to only_if)
  * directory[/var/chef/cache/handlers] action create (up to date)
  * template[/var/chef/cache/handlers/knife_status.rb] action create (up to date)
  * chef_handler[Motd::KnifeStatus] action enable/var/chef/cache/cookbooks/chef_handler/providers/default.rb:58: warning: toplevel constant ChefHandler referenced by Chef::Resource::ChefHandler

    
    ================================================================================
    Error executing action `enable` on resource ‘chef_handler[Motd::KnifeStatus]’
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `new’ for ChefHandler:Module
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:58:in `load_current_resource’
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/motd/recipes/knife_status.rb
    
     56: chef_handler ‘Motd::KnifeStatus’ do
     57:   source ::File.join(Chef::Config[:file_cache_path], ‘handlers’, ‘knife_status.rb’)
     58:   action :enable
     59: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/motd/recipes/knife_status.rb:56:in `from_file’
    
    chef_handler(“Motd::KnifeStatus”) do
      action [:enable]
      default_guard_interpreter :default
      supports {:report=>true, :exception=>true}
      declared_type :chef_handler
      cookbook_name “motd”
      recipe_name “knife_status”
      source “/var/chef/cache/handlers/knife_status.rb”
      class_name “Motd::KnifeStatus”
    end
    
    System Info:
    ------------
    chef_version=13.0.113
    platform=centos
    platform_version=7.3.1611
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=11493;start=15:26:51;
    executable=/opt/chef/bin/chef-client
    

Running handlers:
[2017-04-10T15:27:01-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-10T15:27:01-05:00] ERROR: Exception handlers complete
Chef Client failed. 8 resources updated in 10 seconds
[2017-04-10T15:27:01-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-04-10T15:27:01-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-10T15:27:01-05:00] ERROR: chef_handler[Motd::KnifeStatus] (motd::knife_status line 56) had an error: NoMethodError: undefined method `new’ for ChefHandler:Module
[2017-04-10T15:27:01-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by tas50** [comment]
The fix for this bug has been shipped

**Comment by Stromweld** [comment]
thanks for the quick turnaround on this guys.
